### ISSUE TITLE
Link to paper/manuscript

### ISSUE THREAD

**Issue by saket-maheshwary** [jungtaekkim/automl-challenge-2018#1]
Hi,

Thanks for sharing your work. Could you please share your paper/manuscript accepted in "International Workshop on Automatic Machine Learning at ICML/IJCAI-ECAI" ?

**Comment by jungtaekkim** [comment]
Hello, @sakimahesh 

I think the accepted papers at AutoML workshop are not opened yet.
I will reply the link, after the papers are released.

**Comment by saket-maheshwary** [comment]
Hi @jungtaekkim 
Sure, do let me know once the papers are released.

**Comment by jungtaekkim** [comment]
Hi @sakimahesh 

This is the link to manuscript.

https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxhdXRvbWwyMDE4aWNtbHxneDo1ZTQ3ZGZjMTFmMmU0NGE5

**Comment by saket-maheshwary** [comment]
@jungtaekkim Thanks !
